### ISSUE TITLE
[Bug Report] No GIF button 

### ISSUE THREAD

**Issue by averwhy** [dream-frame/Dream-Frame#14]
NOTE: Discord Source is not trusted. Website dev can no longer update site, so yes download link is broken there.

**Dream Frame Edition**
Dream Frame

**Describe the bug**
The GIF button is non existent

**Expected behavior**
i would like to use that gif button

**Screenshots** - Use Imgur
https://cdn.discordapp.com/attachments/715236039530119259/715312175115141141/unknown.png

**Discord Edition** - Since Dream Frame only supports Powercord, Discord Canary is expected here
Discord Canary

**Mod** - Dream Frame currently only supports Powercord
Powercord

**Comment by averwhy** [comment]
nevermind im dumb... the gif tab is in the emoji tab. facepalming rn

**Comment by KorbsStudio** [comment]
Discord Source is no longer up
