### ISSUE TITLE
Server rings either appear or don't appear, Overlapping folders, & one server underneath the add server button.

### ISSUE THREAD

**Issue by throwaway3241** [dream-frame/Dream-Frame#17]
## Description
I'm not entirely a fan of server rings because they're large. The servers either have a server ring or don't have one. Those that don't have one appear upon hover. Folders also overlap onto other folders & one server is underneath the add server button.

## Screenshots
https://i.imgur.com/a/eoXhHdh.png
https://i.imgur.com/a/UOi3R1A.png
https://i.imgur.com/a/FJNXEM5.png

## Mod
[ ] BetterDiscord

## Discord Channel
[ ] Stable

**Comment by KorbsStudio** [comment]
Already mentioned in known issue on the Black Box server
