### ISSUE TITLE
Dream Frame - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Kyle-Li** [dream-frame/Dream-Frame#4]
The link did not work

**Comment by KorbsStudio** [comment]
What link?
There are many links!!!! Invite link? Raw link? Download link?

**Comment by Kyle-Li** [comment]
Download link

**Comment by KorbsStudio** [comment]
Also do not use Discord sources

**Comment by KorbsStudio** [comment]
If you do not respond soon, the issue will be closed.
